name: Deploy to my EC2 Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug GitHub Secrets (Sanity Check)
        run: |
          echo "EC2 Host: ${{ secrets.EC2_HOST }}"
          echo "EC2 User: ${{ secrets.EC2_USER }}"
          echo "EC2 Port: ${{ secrets.EC2_PORT }}"

      - name: Start SSH agent and add private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_EC2_KEY }}
      - name: Confirm key was added to SSH agent
        run: ssh-add -l  

      - name: Run remote command with SSH debug
        run: |
          ssh -v -o StrictHostKeyChecking=no -p ${{ secrets.EC2_PORT }} \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "cd /home/ubuntu && ls -la"



          
